[project]
name = "rgbd-dataset"
version = "0.0.0"
dependencies = [
    "torch",
    "torchvision",
    "open3d",
    "natsort",
    "opencv-python",
    "hydra-core",
    "numpy<=1.26.4",
]
requires-python = ">=3.8"

[tool.setuptools]
py-modules = []
