[project]
name = "rgbd-dataset"
version = "0.0.0"
dependencies = [
    "torch",
    "torchvision",
    "jax==0.8.1 ; sys_platform == 'darwin'",
    "jax[cuda12]==0.8.1 ; sys_platform == 'linux'",
    "flax==0.12.0",
    "polars>=1.34.0",
    "open3d",
    "natsort",
    "opencv-python",
    "hydra-core>=1.3.2",
    "numpy==2.1.2",
    "viser>=1.0.16",
    "semistaticsim>=0.4.9",
]
requires-python = ">=3.8"

[tool.setuptools]
py-modules = []
