_target_: rgbd_dataset.datasets.RGBD.RGBD
dataset_name: "rgbd"
base_path: /home/anshul/isaac-sim-expts/camera_render
scene: saved_trajectory
width: 1280
height: 720
resized_width: -1
resized_height: -1
sequence_start: 0
sequence_end: -1
sequence_stride: 1
relative_pose: False
depth_scale: 1000.0
point_cloud: true
depth_trunc: 8.0
rgb_dir: rgb
depth_dir: depth
pose_dir: camera_pose
intrinsics_dir: intrinsics