_target_: rgbd_dataset.datasets.Isaacsim2.Isaacsim2
dataset_name: "isaacsim2"
base_path: ???
scene: office
width: 1024
height: 768
fx: 1024.0
fy: 1024.0
cx: 512.0
cy: 384.0
resized_width: -1
resized_height: -1
sequence_start: 0
sequence_end: -1
sequence_stride: 1
relative_pose: False
depth_scale: 6553.5
point_cloud: true
depth_trunc: 10.0
