_target_: rgbd_dataset.datasets.OpenMask3D.OpenMask3D
dataset_name: "openmask3d"
base_path: "/home/kumaraditya/openmask3d/resources"
scene: scene_example
width: 640
height: 480
resized_width: -1
resized_height: -1
sequence_start: 0
sequence_end: -1
sequence_stride: 10
relative_pose: False
depth_scale: 1000.0
point_cloud: true
depth_trunc: 5.0
rgb_dir: color
depth_dir: depth
pose_dir: pose
fx: 1169.621094
fy: 1167.105103
cx: 646.295044
cy: 489.927032
intrinsics_resolution: [968, 1296]
