_target_: rgbd_dataset.datasets.Perpetua.Perpetua
dataset_name: "perpetua"
base_path: ???
scene: 1762285287
width: 640
height: 480
resized_width: -1
resized_height: -1
sequence_start: 0
sequence_end: -1
sequence_stride: 1
relative_pose: False
depth_scale: 1000.0
point_cloud: true
depth_trunc: 5.0
rgb_dir: rgb
depth_dir: depth
pose_dir: poses
intrinsics_dir: calib
mapping_dir: mapping.json
cloud_dir: cloud.json
transform_dir: transform.yaml
schedule_dir: schedule.json
