_target_: rgbd_dataset.datasets.ProcTHOR.ProcTHOR
base_path: ???
split: train
scene: 0
width: 300
height: 300
fx: 62.13203435596426
fy: 62.13203435596426
cx: 150.0
cy: 150.0
resized_width: -1
resized_height: -1
sequence_start: 0
sequence_end: -1
sequence_stride: 50
relative_pose: False
depth_scale: 1000.0
point_cloud: true
depth_trunc: 8.0
