_target_: rgbd_dataset.datasets.Replica.Replica
base_path: ???
scene: room0
width: 1200
height: 680
fx: 600.0
fy: 600.0
cx: 599.5
cy: 339.5
resized_width: -1
resized_height: -1
sequence_start: 0
sequence_end: -1
sequence_stride: 50
relative_pose: False
depth_scale: 6553.5
point_cloud: true
depth_trunc: 8.0
