_target_: rgbd_dataset.datasets.SceneFun3D.SceneFun3D
dataset_name: "scenefun3d"
base_path: "/data/kumaraditya/scenefun3d/test"
scene: "421372"
width: 1920
height: 1440
resized_width: -1
resized_height: -1
sequence_start: 0
sequence_end: -1
sequence_stride: 10
relative_pose: False
depth_scale: 1000
point_cloud: true
depth_trunc: 100.0
