_target_: rgbd_dataset.datasets.SemiStaticSim.SemiStaticSim
dataset_name: "semistaticsim"
# base_path: ???
base_path: /Users/miguelsaavedra/Documents/Projects/SemiStaticSim/generated_data/semistaticsim/test/0/0/privileged
scene: 0
width: 640
height: 640
resized_width: -1
resized_height: -1
sequence_start: 0
sequence_end: -1
sequence_stride: 1
relative_pose: False
depth_scale: 1000.0
point_cloud: true
depth_trunc: 5.0
img_dir: images
rgb_dir: rgb_first_view
depth_dir: depth
semantics_dir: semantics
pose_dir: poses
